version: 2

conda:
    environment: environment.yml

build:
    image: latest

mkdocs:
    configuration: mkdocs.yml

formats: []

python:
    install:
        - method: pip
          path: .
          extra_requirements:
            - mkdocs-material