name: cedar-mkdocs
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.12
  - mkdocs=1.1.2
  - mkdocs-material=5.5.12
  - mkdocs-material-extensions=1.0
  - pymdown-extensions=8.0
  - sphinx_rtd_theme=1.0.0
