name: cedar-mkdocs
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.12
  - mkdocs=1.1.2
  - mkdocs-material-extensions=1.0.3
  - pymdown-extensions=8.0
  - sphinx_rtd_theme=1.0.0
  - pip
  - pip:
      - mkdocs-material==8.5.6
      - mkdocs-markdownextradata-plugin==0.2.5
