site_name: CEDAR
theme:
    name: material

markdown_extensions:
    - markdown.extensions.toc:
          permalink: true
    - pymdownx.details
    - pymdownx.superfences

repo_url: https://github.com/metadatacenter/cedar-project

nav:
    - Home: index.md
    - Install Guides:
        - install-overview.md
        - Developer Install:
            - install-developer/intro.md
            - install-developer/system-architecture.md
            - Prerequisites:
                - install-developer/prereq-macos.md
                - install-developer/prereq-homebrew.md
                - install-developer/prereq-openssl.md
            - Users, directories and passwords:
                - install-developer/user.md
                - install-developer/home-directory.md
                - install-developer/usernames-and-passwords.md
            - Infrastructure services:
                - install-developer/infra-mongodb.md
                - install-developer/infra-elasticsearch.md
                - install-developer/infra-mysql.md
                - install-developer/infra-redis.md
                - install-developer/infra-neo4j.md
        - Production Install:
            - Prerequisites: install-production-prereq.md
        - Docker Install:
            - Prerequisites: install-docker-prereq.md
