site_name: CEDAR
theme:
    name: material

markdown_extensions:
    - markdown.extensions.toc:
          permalink: true
    - pymdownx.keys
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: false

extra_css:
    - stylesheets/extra.css

repo_url: https://github.com/metadatacenter/cedar-project

nav:
    - Home: index.md
    - Install Guides:
        - install-overview.md
        - Developer Install:
            - install-developer/intro.md
            - install-developer/system-architecture.md
            - Prerequisites:
                - install-developer/prereq-macos.md
                - install-developer/prereq-homebrew.md
                - install-developer/prereq-openssl.md
                - install-developer/prereq-jdk.md
                - install-developer/prereq-maven.md
            - Users, directories, passwords and domain:
                - install-developer/user.md
                - install-developer/home-directory.md
                - install-developer/usernames-and-passwords.md
                - install-developer/domain.md
            - Scripts and aliases:
                  - install-developer/scripts-and-aliases-overview.md
                  - install-developer/scripts-and-aliases-install.md
                  - install-developer/scripts-and-aliases-include.md
            - SSL certificates:
                  - install-developer/cert-overview.md
                  - install-developer/cert-self-signed.md
                  - install-developer/cert-install.md
            - CEDAR commands:
                  - install-developer/commands-overview.md
                  - install-developer/commands-cedarenv.md
                  - install-developer/commands-cedarss.md
                  - install-developer/commands-startstop.md
            - Infrastructure services:
                - install-developer/infra-mongodb.md
                - install-developer/infra-elasticsearch.md
                - install-developer/infra-mysql.md
                - install-developer/infra-redis.md
                - install-developer/infra-neo4j.md
